# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20485b19cac5a87570bde0b111a73800e30f032909ad22767ce3d6de2dcdebcea81e9ebab766d9e2c3ca8e8ee5d65b43c1a91a98deff11b35987643e221403ee

test:
  secret_key_base: 126407367c8962a05d5d3ee3efe563e9e1c2a8237f0524f136d29bdf295af1b165ca63e1b9211887ba445e96a9c03d10690ad0afafd5d12c2dc7bf53cb275f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
